"""
Lint Rules
==========
Predefined lint rule lists for voice and style validation.
"""

from typing import Dict, List

# Banned opening phrases - generic, low-value starts
BANNED_OPENERS = [
    "in today's world",
    "in today's digital age",
    "in the modern world",
    "in the current landscape",
    "in this article",
    "in this blog post",
    "in this guide",
    "in this piece",
    "in this post",
    "this article will",
    "this post will",
    "this guide will",
    "we will explore",
    "we'll explore",
    "let's explore",
    "let's dive into",
    "let's take a look at",
    "we'll cover",
    "we will cover",
    "today we're going to",
    "welcome to",
    "have you ever wondered",
    "have you ever asked yourself",
    "do you want to know",
    "are you looking for",
    "are you tired of",
    "are you struggling with",
    "if you're like most",
    "whether you're a beginner",
    "whether you're an expert",
    "as we all know",
    "it's no secret that",
    "it goes without saying",
    "needless to say",
    "obviously",
    "clearly",
    "undoubtedly",
    "without a doubt",
]

# Robotic/AI tell words - overused by LLMs
ROBOTIC_TELLS = [
    "delve",
    "tapestry",
    "unlock",
    "unleash",
    "unravel",
    "embark",
    "journey",
    "landscape",
    "realm",
    "elevate",
    "harness",
    "leverage",
    "synergy",
    "paradigm",
    "holistic",
    "comprehensive",
    "multifaceted",
    "intricate",
    "nuanced",
    "pivotal",
    "paramount",
    "quintessential",
    "unprecedented",
    "revolutionize",
    "transformative",
    "game-changing",
    "cutting-edge",
    "state-of-the-art",
    "best-in-class",
    "world-class",
    "top-tier",
    "seamless",
    "effortless",
    "unparalleled",
    "unmatched",
    "second to none",
    "in a nutshell",
    "at the end of the day",
    "when it comes to",
    "in terms of",
    "with respect to",
    "as a matter of fact",
    "the fact of the matter is",
    "it's worth noting",
    "it's important to note",
    "it's crucial to understand",
    "it's essential to recognize",
    "it's vital to note",
    "it's imperative to understand",
    "it's fundamental to grasp",
    "it's critical to realize",
    "it's necessary to appreciate",
    "it's valuable to consider",
    "it's beneficial to examine",
    "it's useful to explore",
    "it's helpful to understand",
    "it's enlightening to see",
    "it's fascinating to discover",
    "it's intriguing to observe",
    "it's remarkable to witness",
    "it's astonishing to find",
    "it's surprising to learn",
    "it's eye-opening to realize",
    "it's mind-blowing to discover",
    "it's game-changing to implement",
    "it's revolutionary to adopt",
    "it's transformative to embrace",
    "navigate",
    "navigating",
    "navigate through",
    "navigate the complexities",
    "navigate the challenges",
    "navigate the landscape",
    "deep dive",
    "deep-dive",
    "deeply understand",
    "thoroughly examine",
    "comprehensively cover",
    "extensively explore",
    "meticulously analyze",
    "systematically approach",
    "strategically align",
    "proactively address",
    "effectively manage",
    "efficiently optimize",
    "successfully implement",
    "consistently deliver",
    "continuously improve",
    "relentlessly pursue",
    "passionately commit",
    "wholeheartedly embrace",
    "genuinely care",
    "authentically connect",
    "transparently communicate",
    "collaboratively solve",
    "innovatively approach",
    "creatively solve",
    "dynamically adapt",
    "agilely respond",
    "resiliently overcome",
    "sustainably grow",
    "exponentially scale",
    "dramatically improve",
    "significantly enhance",
    "substantially increase",
    "considerably reduce",
    "remarkably accelerate",
    "exceptionally perform",
    "outstandingly achieve",
    "extraordinarily succeed",
    "phenomenally transform",
    "miraculously solve",
    "magically fix",
    "instantly resolve",
    "effortlessly master",
    "seamlessly integrate",
    "flawlessly execute",
    "perfectly align",
    "ideally suit",
    "optimally configure",
    "maximally leverage",
    "minimally disrupt",
    "seamlessly transition",
    "smoothly migrate",
    "gracefully handle",
    "elegantly solve",
    "beautifully designed",
    "masterfully crafted",
    "exquisitely tuned",
    "perfectly balanced",
    "harmoniously blend",
    "synergistically combine",
    "holistically address",
    "comprehensively solve",
    "end-to-end",
    "full-stack",
    "all-encompassing",
    "all-inclusive",
    "all-round",
    "across the board",
    "across the spectrum",
    "end-to-end solution",
    "complete solution",
    "total solution",
    "integrated solution",
    "unified solution",
    "seamless experience",
    "unified experience",
    "cohesive experience",
    "holistic experience",
    "immersive experience",
    "engaging experience",
    "delightful experience",
    "memorable experience",
    "remarkable experience",
    "exceptional experience",
    "extraordinary experience",
    "unforgettable experience",
    "game-changing experience",
    "revolutionary experience",
    "transformative experience",
]

# Formal phrases that should be simplified
FORMAL_PHRASES = {
    "utilize": "use",
    "utilise": "use",
    "leverage": "use",
    "employ": "use",
    "implement": "do",
    "execute": "do",
    "facilitate": "help",
    "enable": "let",
    "empower": "let",
    "optimize": "improve",
    "optimise": "improve",
    "maximize": "get the most from",
    "maximise": "get the most from",
    "minimize": "reduce",
    "minimise": "reduce",
    "enhance": "improve",
    "augment": "add to",
    "supplement": "add to",
    "complement": "go with",
    "mitigate": "reduce",
    "alleviate": "ease",
    "ameliorate": "improve",
    "expedite": "speed up",
    "accelerate": "speed up",
    "facilitate": "make easier",
    "streamline": "simplify",
    "rationalize": "simplify",
    "consolidate": "combine",
    "integrate": "combine",
    "synchronize": "sync",
    "harmonize": "align",
    "standardize": "make consistent",
    "normalize": "make normal",
    "formalize": "make official",
    "institutionalize": "make standard",
    "operationalize": "put into practice",
    "actualize": "make real",
    "realize": "make happen",
    "materialize": "make happen",
    "conceptualize": "think of",
    "envision": "imagine",
    "visualize": "picture",
    "strategize": "plan",
    "prioritize": "focus on",
    "categorize": "group",
    "classify": "group",
    "segment": "split",
    "differentiate": "tell apart",
    "discriminate": "tell apart",
    "distinguish": "tell apart",
    "characterize": "describe",
    "epitomize": "be the perfect example of",
    "exemplify": "show",
    "illustrate": "show",
    "demonstrate": "show",
    "manifest": "show",
    "exhibit": "show",
    "display": "show",
    "evince": "show",
    "indicate": "show",
    "signify": "mean",
    "denote": "mean",
    "connote": "suggest",
    "imply": "suggest",
    "infer": "conclude",
    "deduce": "figure out",
    "derive": "get",
    "extract": "get",
    "obtain": "get",
    "acquire": "get",
    "procure": "get",
    "secure": "get",
    "garner": "get",
    "glean": "get",
    "ascertain": "find out",
    "determine": "decide",
    "establish": "set up",
    "institute": "set up",
    "initiate": "start",
    "commence": "start",
    "embark on": "start",
    "launch": "start",
    "inaugurate": "start",
    "instigate": "start",
    "catalyze": "spark",
    "precipitate": "cause",
    "engender": "cause",
    "beget": "cause",
    "generate": "create",
    "produce": "make",
    "yield": "give",
    "render": "make",
    "furnish": "give",
    "provide": "give",
    "supply": "give",
    "deliver": "give",
    "offer": "give",
    "extend": "give",
    "present": "give",
    "proffer": "give",
    "tender": "give",
    "submit": "give",
    "propose": "suggest",
    "recommend": "suggest",
    "advocate": "support",
    "champion": "support",
    "endorse": "support",
    "subscribe to": "agree with",
    "adhere to": "follow",
    "comply with": "follow",
    "conform to": "follow",
    "abide by": "follow",
    "observe": "follow",
    "respect": "follow",
    "honor": "follow",
    "uphold": "keep",
    "maintain": "keep",
    "sustain": "keep",
    "preserve": "keep",
    "conserve": "keep",
    "retain": "keep",
    "perpetuate": "keep going",
    "prolong": "extend",
    "extend": "make longer",
    "lengthen": "make longer",
    "expand": "grow",
    "increase": "grow",
    "grow": "grow",
    "develop": "grow",
    "evolve": "change",
    "progress": "move forward",
    "advance": "move forward",
    "proceed": "go on",
    "continue": "keep going",
    "persist": "keep going",
    "persevere": "keep going",
    "endure": "last",
    "survive": "last",
    "prevail": "win",
    "triumph": "win",
    "succeed": "work",
    "achieve": "do",
    "accomplish": "finish",
    "attain": "reach",
    "reach": "get to",
    "arrive at": "get to",
    "gain": "get",
    "secure": "get",
    "obtain": "get",
    "acquire": "get",
    "win": "get",
    "earn": "get",
    "merit": "deserve",
    "deserve": "deserve",
    "warrant": "deserve",
    "justify": "prove right",
    "validate": "prove right",
    "verify": "check",
    "confirm": "check",
    "corroborate": "back up",
    "substantiate": "prove",
    "authenticate": "prove real",
    "certify": "approve",
    "accredit": "approve",
    "authorize": "allow",
    "sanction": "allow",
    "approve": "okay",
    "endorse": "support",
    "ratify": "make official",
    "formalize": "make official",
    "legitimize": "make legitimate",
    "legalize": "make legal",
    "decriminalize": "make legal",
    "legitimate": "real",
    "authentic": "real",
    "genuine": "real",
    "bona fide": "real",
    "valid": "works",
    "sound": "solid",
    "robust": "strong",
    "resilient": "tough",
    "stalwart": "reliable",
    "steadfast": "steady",
    "unwavering": "steady",
    "unshakeable": "solid",
    "unflinching": "brave",
    "undaunted": "brave",
    "intrepid": "brave",
    "fearless": "brave",
    "courageous": "brave",
    "valiant": "brave",
    "heroic": "brave",
    "gallant": "brave",
    "noble": "good",
    "virtuous": "good",
    "righteous": "right",
    "upstanding": "honest",
    "principled": "has principles",
    "ethical": "fair",
    "moral": "right",
    "honorable": "honest",
    "reputable": "trusted",
    "esteemed": "respected",
    "distinguished": "stands out",
    "eminent": "famous",
    "illustrious": "famous",
    "renowned": "famous",
    "celebrated": "famous",
    "acclaimed": "praised",
    "lauded": "praised",
    "extolled": "praised",
    "venerated": "respected",
    "revered": "respected",
    "adored": "loved",
    "cherished": "loved",
    "treasured": "valued",
    "prized": "valued",
    "coveted": "wanted",
    "sought-after": "wanted",
    "desirable": "wanted",
    "appealing": "attractive",
    "attractive": "good-looking",
    "alluring": "tempting",
    "enticing": "tempting",
    "seductive": "tempting",
    "captivating": "holds attention",
    "mesmerizing": "holds attention",
    "spellbinding": "holds attention",
    "enchanting": "charming",
    "bewitching": "charming",
    "charismatic": "charming",
    "magnetic": "draws people",
    "compelling": "convincing",
    "persuasive": "convincing",
    "convincing": "makes sense",
    "cogent": "clear",
    "forceful": "strong",
    "powerful": "strong",
    "potent": "strong",
    "efficacious": "works",
    "effective": "works",
    "efficient": "works well",
    "productive": "gets results",
    "fruitful": "works",
    "successful": "wins",
    "triumphant": "wins",
    "victorious": "wins",
}

# Hedging phrases to minimize
HEDGING_PHRASES = [
    "may", "might", "could", "would", "should",
    "perhaps", "possibly", "potentially", "presumably",
    "seemingly", "apparently", "reportedly", "allegedly",
    "somewhat", "rather", "quite", "fairly", "relatively",
    "to some extent", "in a sense", "in a way", "sort of", "kind of",
    "almost", "nearly", "virtually", "practically", "essentially",
    "basically", "fundamentally", "largely", "mainly", "mostly",
    "generally", "typically", "usually", "commonly", "often",
    "tends to", "seems to", "appears to", "looks like", "sounds like",
    "it seems", "it appears", "it looks like", "it sounds like",
    "one might say", "one could argue", "it could be argued",
    "it is possible that", "it is likely that", "it is probable that",
    "there is a chance that", "there is a possibility that",
]

# Em dash pattern
EM_DASH_PATTERN = r'[—–-]{2,}'

# Contraction map for checking
CONTRACTION_MAP = {
    "don't": "do not",
    "can't": "cannot",
    "won't": "will not",
    "wouldn't": "would not",
    "shouldn't": "should not",
    "couldn't": "could not",
    "isn't": "is not",
    "aren't": "are not",
    "wasn't": "was not",
    "weren't": "were not",
    "haven't": "have not",
    "hasn't": "has not",
    "hadn't": "had not",
    "doesn't": "does not",
    "didn't": "did not",
    "it's": "it is",
    "that's": "that is",
    "what's": "what is",
    "who's": "who is",
    "where's": "where is",
    "when's": "when is",
    "why's": "why is",
    "how's": "how is",
    "there's": "there is",
    "here's": "here is",
    "i'm": "i am",
    "you're": "you are",
    "we're": "we are",
    "they're": "they are",
    "he's": "he is",
    "she's": "she is",
    "it'll": "it will",
    "i'll": "i will",
    "you'll": "you will",
    "we'll": "we will",
    "they'll": "they will",
    "i've": "i have",
    "you've": "you have",
    "we've": "we have",
    "they've": "they have",
    "i'd": "i would",
    "you'd": "you would",
    "he'd": "he would",
    "she'd": "she would",
    "we'd": "we would",
    "they'd": "they would",
    "let's": "let us",
}

# Minimum sentence variety thresholds
SENTENCE_VARIETY_MIN = 30.0  # % short sentences (<10 words)
SENTENCE_VARIETY_MAX = 25.0  # % long sentences (>25 words)


def get_all_rules() -> Dict[str, List[str]]:
    """Get all lint rules as a dictionary."""
    return {
        "banned_openers": BANNED_OPENERS,
        "robotic_tells": ROBOTIC_TELLS,
        "formal_phrases": list(FORMAL_PHRASES.keys()),
        "hedging_phrases": HEDGING_PHRASES,
    }